title: Thingy Ma Jig
email: webmaster@thingy-ma-jig.co.uk
description: > # this means to ignore newlines until "baseurl:"
  TODO!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: ThingyMaJig/ThingyMaJig.github.io


timezone: Europe/London
port: 9000
host: 127.0.0.1
exclude:
  - README.md
  - Gemfile.lock
  - Gemfile
gems:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-seo-tag
  - jekyll-sitemap
paginate: 10
sass:
  style: compressed
excerpt_separator: <!--break-->

collections:
  my_categories:
    output: true
    permalink: /tags/:name/

defaults:
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category

# CANNOT CHANGE THESE
lsi: false
safe: true
#incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax